### ISSUE TITLE
Monitor derivatives during runtime?

### ISSUE THREAD

**Issue by drf777** [neurophysik/jitcode#10]
I'm using the latest version of JitCode (downloaded in late 2018), and it seems to work and my generators seem to be fine. However, the integrated solutions are not what I expect, so I would like to actually monitor the derivatives to better understand what is going on. Is there an easy way to print out the derivatives at each time step?

**Comment by Wrzlprmft** [comment]
If `ODE` is your `jitcode` instance (i.e., your integrator object), you can access the derivative (as soon as compiled) with `ODE.f`. It is a Python function that has the same signature as required by `scipy.ode`, i.e., `f(t,y)`. To get the actual value, give it the current time and state as arguments. Thus `ODE.f(ODE.t,ODE.y)` always gives you the current derivative.

Here is a minimal working example that uses this:

``` Python
from jitcode import jitcode, y

ODE = jitcode([-y(0)])
ODE.set_integrator("dopri5")
ODE.set_initial_value([1],0.0)

for time in range(30):
	ODE.integrate(time)
	print(ODE.f(ODE.t,ODE.y))
```

Note, however, that each sampling step (at which you can compute the derivatives externally) can consist of many integration steps. If your derivative goes nuts within a small time frame, you will may not be able to see it this way (but then your integration will probably not finish anyway).

**Comment by drf777** [comment]
Thank you. That worked great!
