### ISSUE TITLE
Using Solve_ivp methods

### ISSUE THREAD

**Issue by edroque17** [neurophysik/jitcode#11]
Hi there,

I am using Jitcode for simulating a network dynamics. I know that the vector field presents different time scales, so it is desirable using Implicit Methods. Just for curiosity I tried to use any method from Solve_ivp and I can not. The error is the following: <method-wrapper '__init__' of NoneType object at 0x556c9b3dc560> is not a Python function

I have no guess what is going on. Do you have an explanation?
(I am not so used to use scipy.integrate - so this may be explain it).

Thank you,
Edmilson Roque.

**Comment by Wrzlprmft** [comment]
Without any details, I have no idea. Can you please do the following:

1. Tell me your Python, SciPy, and JiTCODE version. Run this in Python:

     ``` Python
    import scipy
    import jitcode
    from sys import version
    print(version)
    print(scipy.__version__)
    print(jitcode.__version__)
     ```

2. Run all tests. The easiest way to do this should be to run the following in a shell:

    ``` shell
    git clone https://github.com/neurophysik/jitcode
    cd jitcode/tests
    ./all_tests.sh
    ```

    If any test fails, please tell me the entire output.

3. If no test fails in the above, try to reduce your code to a [minimal example](https://stackoverflow.com/help/mcve) and post this.
