### ISSUE TITLE
Symbol t not recognized as Real

### ISSUE THREAD

**Issue by drf777** [neurophysik/jitcode#13]
From _jitcode.py:

`t = symengine.Symbol("t", real=True)`

So `t` should be Real. But when I try a simple separation of real and imaginary parts:

```
from symengine import I, exp
from jitcode import y, t
from sympy import re, im
a = exp(-I*t)
print(re(a))
```
I get:

`exp(im(t))*cos(re(t))`

In Sympy tutorials when they declare a Symbol as `real=True`, the above does not happen (get properly `cos(t)` )

I am having same problem with `y`, although in _jitcode.py it is not declared as Real:

`y = symengine.Function("y")`

Since jitcode requires functions `y` to be real (cannot calculate with `y` Imaginary), my intent is to set `v = y(1) + I*y(2)` and then later separate out Real and Imaginary parts after multiplying by other terms in my program, then submit to jitcode `.integrate` as separate Real and Imaginary relations.

I tried looking for a Symengine version of `re` and `im`, but no luck, so I assume the Sympy `re` and `im` should work.

Please advise. Otherwise, I will have to manually separate Real and Imaginary parts out of a fairly complicated equation. Thanks in advance.

**Comment by Wrzlprmft** [comment]
SymEngine not supporting real parts is a SymEngine issue you have to [raise there](https://github.com/symengine/symengine.py/issues). Until now, it never mattered for JiTCODE, so I simply didn’t notice.

That being said, JiTCODE is able to deal with pure SymPy input ([test](https://github.com/neurophysik/jitcode/blob/master/tests/test_sympy_input.py)); it will just be slower (which should not matter for all but very big differential equations). So, I suggest that you start with:

``` Python3
from jitcode import jitcode
import sympy
t = sympy.Symbol("t", real=True)
y = sympy.Function("y")
```

Should this cause any problems, please report them. You can also do also do all the preparation purely in SymPy and then convert to SymEngine.

**Comment by drf777** [comment]
Yes, I see how your test works. Note that if you had tried sympy.re(cos(t)) in your test you would have got the same issue as me.

I did some further tests, and you are correct that it seems to be a symengine issue, so I submitted an issue to them. Basically, `sympy.re` and `sympy.im` are apparently incompatible with symengine, yet I could find no equivalent `symengine.re` or `symengine.im` (or other methods like `.real()` or `.real_part()`).

I will post the result here if symengine provides one.

However, I am intrigued by your idea of doing all the equation generation in sympy and then convert to symengine. Can you provide a hint how to do this? I imagine something like:

```
from sympy import Symbol, I, exp, cos, sin, re, im
from jitcode import y,t

x = Symbol("x", real = True)
f = exp(I*x)
...
real_eqn = re(...)
imag_eqn = im(...)
```

But how would you then substitute jitcode `t` for sympy `x` ?

**Comment by Wrzlprmft** [comment]
*Weird: I thought I replied to this two days ago. Anyway, here is my delayed response.*

> Can you provide a hint how to do this?

JiTCODE accepts SymPy symbols as input. The main difference is that initialising the integrator can be considerably slower this way, but that should only matter for very large differential equations.

For example:

``` Python 3
from jitcode import jitcode
from sympy import re, im, I, exp, Symbol, Function

t = Symbol("t", real=True)
y = Function("y", real=True)

z = y(0)+I*y(1)
f = [
		re(exp(I*t)*z),
		im(exp(I*t)*z),
	]

ODE = jitcode(f)
ODE.set_integrator("dopri5")
ODE.set_initial_value([1.0,0.0],0.0)
ODE.integrate(10)
```

> But how would you then substitute jitcode `t` for sympy `x` ?

In general SymEngine’s `sympify` (sic) would be my first choice for this and this is what JiTCODE uses internally. But then again, you only need to use this if JiTCODE and thus `sympify` fail to handle your case. So, in that unlikely event, I would have to look at the specific case and why it fails.

**Comment by drf777** [comment]
Apparently symengine did not implement assumptions in the Symbol declarations: [https://github.com/symengine/symengine.py/issues/286#issuecomment-497502971]

> symengine doesn't have support for assumptions yet. So, `x = Symbol('x', real=True)` is equivalent to `x = Symbol('x')` (There should be a warning there saying `real=True` is disregarded.)

Apparently `t = sympy.Symbol("t", real=True)` in jitcode is not recognizing `t` as Real if symengine is being used. I suppose there may be a potential fix in jitcode to accommodate this, perhaps automatically doing a conversion such as you outlined above always for `t`.

**Comment by Wrzlprmft** [comment]
> Apparently `t = sympy.Symbol("t", real=True)` in jitcode is not recognizing `t` as Real if symengine is being used.

I fail to understand this. JiTCODE is not using the above code. With a few isolated exceptions, JiTCODE uses SymEngine entirely (for speed reasons).

> I suppose there may be a potential fix in jitcode to accommodate this, perhaps automatically doing a conversion such as you outlined above always for `t`.

I won’t change the default importable `t` and `y` to SymPy, since it would considerably slow down the compilation of larger systems.

However, what I just implemented is providing alternative symbols in a submodule. With the latest version from GitHub (install via `pip3 install git+git://github.com/neurophysik/jitcode --user` or similar), you can now do the following:

``` Python 3
from jitcode import jitcode
from jitcode.sympy_symbols import y,t
from sympy import re, im, I, exp

z = y(0)+I*y(1)
f = [
		re(exp(I*t)*z),
		im(exp(I*t)*z),
	]

ODE = jitcode(f)
ODE.set_integrator("dopri5")
ODE.set_initial_value([1.0,0.0],0.0)
ODE.integrate(10)
```

**Comment by drf777** [comment]
Sorry. I typed wrong. The _jitcode.py line 25 did indeed use symengine, not sympy:

`t = symengine.Symbol("t", real=True)`

Thanks for updating jitcode.
