### ISSUE TITLE
Question: exact meaning of absolute accuracy of the integration for vectors

### ISSUE THREAD

**Issue by wjadvos** [neurophysik/jitcode#15]
I have a question about the meaning of the absolute error for integration of vectors: is this the accurucay of each component, or of the whole vector using some kind of norm? And for the following code:

 I = jitcode(kuramotos_f,n=n)
 I.set_integrator("dop853",atol=1e-7,rtol=0)

  initial_state = uniform(0,2*pi,n)
 I.set_initial_value(initial_state,time=0.0)

   times = range(0,totaltime,totaltime*20)

Is the absulute error a cut-off error for the error for moving from one moment in "times" to the next (so from t to t+0.05)?

**Comment by Wrzlprmft** [comment]
> is this the accurucay of each component, or of the whole vector using some kind of norm?

Strictly speaking, this depends on the underlying integrator used, but at least for the integrators from Solve IVP it is component-wise, i.e., a step is regarded as not successful if the error is exceeded in a single component. This is also the de facto standard.

> Is the absulute error a cut-off error for the error for moving from one moment in "times" to the next (so from t to t+0.05)?

No, it is an error for a single integration step, of which there can be several for moving from one of your moments to the other.
