### ISSUE TITLE
Add external input

### ISSUE THREAD

**Issue by jajcayn** [neurophysik/jitcode#16]
Dear developer,

I started playing with `jitcode` not that long ago and I wondered whether it's possible to somehow include an external input. We are not speaking about noise (so no SDEs, the system is complex ODEs with ~30 variables - computational neuroscience).

I'd need to include input as an external time series (to be precise, the external time series will be sinusoidal spike train modeled as moving Poisson process, filtered with impulse-response function), so let's say we will integrate for 20k time steps, and I'd create a time series of external input of the same length beforehand. Is it possible to include such input to the model equations? I guess some `symengine` symbol would do, but I wasn't able to find out how to correctly populate it with values.

Thanks a lot!
Best,
N.

**Comment by Wrzlprmft** [comment]
It’s not that easy, but to explain why and what the alternatives are: Can you be a bit more specific as to what your input looks like? My best guess so far is that you have no input most of the time and short finite pulses in case of a spike.

**Comment by jajcayn** [comment]
Hey, thanks for the response.
Sure, I prepared a small demo with typical parameter values as per papers:

First we create a sinusoidal rate signal and generate spike times via inhomogeneous Poisson process (using `elephant` library for that)
```python
# params
dt = 1e-4  # dt=0.1ms
time_vector = np.arange(0., 10., dt) # 0-10 seconds,
sampling_rate = 1./dt
max_rate = 20 # Hz
sinusoid_duration = 3. # second
spike_amplitude = 2. # mV

# sinusoidal rate
sin_ = (
    np.sin((2.0 / sinusoid_duration) * np.pi * time_vector)
    + 1.0
)
sin_ *= max_rate / 2.0
# transform to AnalogSignal
sin_profile = AnalogSignal(
    sin_[:, np.newaxis],
    units="Hz",
    sampling_rate=sampling_rate * Hz,
    t_start=0. * s,
)
# generate spike times
spike_times = inhomogeneous_poisson_process(rate=sin_profile, as_array=True)
```

the sinusoidal signal looks like
![sin_sig](https://user-images.githubusercontent.com/6525217/66827620-5e983900-ef4f-11e9-8804-241ec4ecfce5.png)
and the spike times then
![spike_times](https://user-images.githubusercontent.com/6525217/66827634-6526b080-ef4f-11e9-9e3a-7119825cd0ba.png)

Now, the spike times are converted to timeseries of voltage as
```python
# spiketimes to timeseries
train_timeseries = np.zeros((time_vector.shape[0],))
spike_occurences = (spike_times * sampling_rate).astype(
    np.int
)
train_timeseries[spike_occurences] = spike_amplitude
```

so the timeseries looks like
![spike_ts](https://user-images.githubusercontent.com/6525217/66827700-87203300-ef4f-11e9-8099-95452ccbec50.png)
The spikes are considered a point process without any temporal evolution by themselves (often done in neural mass modelling).

Finally, filtering as:
```python
def impulse_response(time, gain, time_constant):
    return (gain * time_constant * time * np.exp(-time_constant * time) * np.heaviside(time, 0.0))

# generate impulse_response
imp_resp = impulse_response(time_vector, gain, time_constant)

# convolve with signal
input_signal = np.convolve(train_timeseries, imp_resp, mode="full")[: train_timeseries.shape[0]]
```

results in:
![imp_resp](https://user-images.githubusercontent.com/6525217/66827804-ca7aa180-ef4f-11e9-9d81-edf6e1eb8c3c.png)
![final_inp](https://user-images.githubusercontent.com/6525217/66827809-cea6bf00-ef4f-11e9-94ee-04fdb59745f0.png)

The last image is considered a final input timeseries. So, although random (Possion process), the timeseries has fine structure, and as far as I know, cannot be modelled as SDEs. Before using `jitc*de` I was generating this input before the integration (I already knew the integration times and dt, so creating a `time_vector` was not a problem) and then feeding the input by timesteps to the intergator. 

In the meantime I (kind of stupidely) tried to make a timeseries before hand and than pass it as a generator to the derivates (something like a `next(ext_input)`, where `ext_input=iter(input.tolist())`) but the generator is called only once, and the best shot I got was to introduce `symengine` symbol into the functions, but I couldn't find a way how to populate it with correct values.

Hope this was clear! Thanks for the reply!

**Comment by Wrzlprmft** [comment]
> Before using `jitc*de` I was generating this input before the integration (I already knew the integration times and dt, so creating a `time_vector` was not a problem) and then feeding the input by timesteps to the intergator.

Well, here is the problem: JiTCODE (and many other ODE tools) uses integrators which adapt the step size (to the “difficulty” of the integration). This means you cannot know beforehand at which time you will need to evaluate your input. Whatever you use to supply the input must be able to provide it at an arbitrary time, e.g., via interpolation.

Now, there are many general ways to address this:

* You use a Python function to evaluate your input. SciPy’s [regular integrators](https://docs.scipy.org/doc/scipy/reference/integrate.html#solving-initial-value-problems-for-ode-systems) all support this. JiTCODE however doesn’t, because the function evaluation would be somewhat tedious to implement and be inevitably slow, so you wouldn’t fully benefit of JiTCODE’s main feature, the just-it-time compilation anyway.

* You can use a dedicated engine that also speeds up the interpolation and integrates it with the integration. I actually implemented this in [JiTCDDE](https://jitcdde.readthedocs.io) where it is used to access the past of a delay differential equation. You can abuse this as follows:

    1. Use the past of an arbitrary dynamical variable, say *y*(0) to store your spike train in a reasonable manner (e.g., by not wasting any interpolation points on the spike-free intervals).
    2. Where you want to use your input, use `y(0,t-20000)` instead.

    This should be rather fast, but may create some considerable memory overhead since it tries to store the entire past.

* You hard-code the spike input with changing parameters. To keep things simple first, let’s suppose that your spikes do not overlap. 

    1. Write a symbolic function `spike(time)` that describes the profile of a spike at `time`.
    2. Use this as your spike input.
    3. Make `time` a [parameter of your dynamics](https://jitcode.readthedocs.io#_jitcode.jitcode.set_parameters).
    4. Set the parameter `time` to the time of your first spike.
    5. Integrate until the first spike is completely over.
    6. Set the parameter `time` to the time of your second spike.
    7. Integrate until the second spike is completely over.
    8. …

    If you want spikes to overlap use `spike(time_1) + spike(time_2) + …` instead and adjust it accordingly. This is somewhat tedious but particularly if your driven dynamics complicated, this can be the most efficient solution, as the only overhead is changing the parameter (`time`) from time to time, which will be negligible compared to the integration effort for complicated dynamics.

**Comment by jajcayn** [comment]
thanks for a beautiful and insightful response! I'll look into it

**Comment by jajcayn** [comment]
Hey, so I went on and tried to implement the last solution you proposed (the past of `y` doesn't seem reasonable, since I'll be using actual DDEs in the end and it'd be a mess with some past being the actual past and some of it just a storage for input).

Before thinking how to actually implement a spike function I just tried very simple "noise generator", something like:
```python
def get_noise(time):
    np.random.seed()
    return np.random.normal(0., 0.5)
```
so explicitly playing the game that my noise depends on time. When I register the helper as 
```
noise = Symbol("noise")
helpers = [( noise, get_noise(t))]
```
with `t` being the time vector from `jitcdde` and then registering the helpers, I got the feeling that the helper is called only once since I can see one "bump" in the solution in the beginning, but then the solution is very smooth, so I figure no noise is added. Am I doing something wrong? Shouldn't I use helpers with the symbolic function `spike(time)` (or in my simple case `get_noise(t)`)?

**Comment by Wrzlprmft** [comment]
> Hey, so I went on and tried to implement the last solution you proposed (the past of `y` doesn't seem reasonable, since I'll be using actual DDEs in the end and it'd be a mess with some past being the actual past and some of it just a storage for input).

If you are using DDEs in the end anyway, it actually makes even more sense to do it this way, since you have the overhead of using the DDE integrator anyway. To avoid stuff mixing up, just store your input in an extra dynamical variable that you do not use (make its derivative zero).

> Then finally, registering the helpers, I got the feeling that the helper is called only once since I can see one "bump" in the solution in the beginning, but then the solution is very smooth, so I figure no noise is added. Am I doing something wrong? Shouldn't I use helpers with the symbolic function `spike(time)` (or in my simple case `get_noise(t)`)?

No, helpers won’t help you with this at all (pun not intended). The problem is that the output of `get_noise` depends on more than the input and it does not return a symbolic function (like `sympy.sin`). Here is a minimal example of how to implement spikes in the way we are talking about:

``` Python3
import numpy as np
from symengine import exp, Symbol
from jitcode import jitcode,y,t

def spike(spike_time,amplitude,width):
	return amplitude*exp(-((t-spike_time)/width)**2)

spike_time = Symbol("spike_time")
f = [
		0.1*y(0) + spike(spike_time,10,0.1)
	]

ODE = jitcode( f, control_pars=[spike_time], verbose=False )
ODE.set_integrator("dopri5")
ODE.set_initial_value([1])

ODE.set_parameters(5.0)
for time in np.arange(0,10,0.1):
	print(*ODE.integrate(time))

ODE.set_parameters(15.0)
for time in ODE.t + np.arange(0,10,0.1):
	print(*ODE.integrate(time))
```

**Comment by jajcayn** [comment]
ou, so actually using the past of new state variables makes sense! Thanks a lot. So I'll just populate my state vector with "noise" values (spikes). Do I do that using `DDE. add_past_points` or `DDE. past_from_function`? Thanks for the example! <3

**Comment by Wrzlprmft** [comment]
> Do I do that using `DDE. add_past_points` or `DDE. past_from_function`?

`DDE.past_from_function` is only a convenience function that uses `DDE.add_past_points` under the hood. I would start by figuring out a simple cubic Hermite interpolant of a single spike. It may help to understand and play with [CHSPy](https://chspy.readthedocs.io) for a bit. Then, just add up all your spikes. If you have overlapping spikes, this may be a bit more complicated, but I can easily add a functionality to sum interpolants to CHSPy.

**Comment by Wrzlprmft** [comment]
> I can easily add a functionality to sum interpolants to CHSPy.

… and done. The latest version of CHSPy contains a function to add splines. This way, you should be able to easily and efficiently define your past consisting of arbitrary placed spikes.

**Comment by Wrzlprmft** [comment]
I created a more explicit example of how to implement an external input [here](https://github.com/neurophysik/jitcdde/issues/25#issuecomment-553318211), in case this helps you.

**Comment by jajcayn** [comment]
that is a nice one! I think I understand and have all the pieces of a puzzle together, I am going to try and implement! Thanks again for your tremendous help on this one!

**Comment by Wrzlprmft** [comment]
You will probably be interested in [this](https://github.com/neurophysik/jitcdde/issues/25#issuecomment-593642018).
