### ISSUE TITLE
Monitor variables that are not in the state vector

### ISSUE THREAD

**Issue by jajcayn** [neurophysik/jitcode#17]
Dear developer,

I encountered an issue that I am not really sure how to address. The MWE would be having two neuronal populations in the mass model. The average membrane potential per population is the sum of weighted synaptic inputs from other populations, hence
![a](https://latex.codecogs.com/gif.latex?v(t)&space;=&space;\sum\limits_{j}&space;C_{ij}y_{j}(t)&space;&plus;&space;I_{ext})
from the voltage, one can compute the firing rate as
![b](https://latex.codecogs.com/gif.latex?r%28t%29%3D%5Cfrac%7BR_%7Bmax%7D%7D%7B1%20&plus;%20%5Cmathrm%7Bexp%7D%28V_%7Bthr%7D%20-%20v%28t%29%29/%5Csigma%29%7D)
and finally, the firing rate is used in second order ODE as
![c](https://latex.codecogs.com/gif.latex?%5Cddot%7By%7D%20%3D%20G%5Comega%20r%28t%29%20-%202%5Comega%5Cdot%7By%7D%20-%20%5Comega%5E2y%28t%29)

For this simple system with two populations I wrote a function as:
```python
def get_firing_rate(voltage):
    return 50. / (1.0 + exp((5.0 - voltage) / 1.79))

def nmm():
    y_pyr, dy_pyr, y_inh, dy_inh = [y(i) for i in range(4)]
    v_pyr = sum(conn[0, i] * y(2*i) for i in range(2))
    v_inh = sum(conn[1, i] * y(2*i) for i in range(2))

    r_pyr = get_firing_rate(v_pyr)
    r_inh = get_firing_rate(v_inh)
    
    d_y_pyr = dy_pyr
    d_dy_pyr = g * omega * r_pyr - 2*omega*dy_pyr - omega * omega*y_pyr
    d_y_inh = dy_inh
    d_dy_inh = g * omega * r_inh - 2*omega*dy_inh - omega * omega*y_inh
    
    return [d_y_pyr, d_dy_pyr, d_y_inh, d_dy_inh]
```
and the system works and can be easily integrated using `jitcode`. However, when analysing the output of the system I am not really interested in the individual values of _y_ but rather I'd like to "monitor" the voltage _v(t)_ and the firing rate r_(t)_, so the variables I am computing within the function and are not part of the state vector. Is this possible? I tried to register firing rate and voltage as a helpers, hence computing them before each integration step, but wasn't able to get helpers' value in each time step. Is that possible? If not, is there any trick you'd recommend for monitoring variables like this?

N.B. this was just a playground, my real system would be much more complex, so more variables to monitor. I'd love to find some scalable solution.

Thanks a million times!
Best,
N.

**Comment by Wrzlprmft** [comment]
What you can always do is to repeat the calculation you do to obtain the variables with the solution. Since this is easily vectorisable, it shouldn’t take much computational time.

Apart from this, there is no way to observe the variables. The reason for this is that the above workaround is rather easy, while it’s tedious to implement and computationally expensive to store this data during the actual integration.
