### ISSUE TITLE
Fixing -fopenmp in clang (MacOS) to run jitcode

### ISSUE THREAD

**Issue by hokanoei** [neurophysik/jitcode#19]
Hello and thanks for developing this python package!

OS specifics: MacOs Catalina (10.15.6), 
jitcode version (1.5.1.dev5+g4bc0683) on python3.8.
The compiler adopted is clang (version 10.0.0). 

Issue: importing jitcode is successful both in bash and IDE 
interfaces. However, running jitcode.test() yields the error: 

>>> import jitcode
>>> jitcode.test()
clang: error: unsupported option '-fopenmp'
error: command 'clang' failed with exit status 1

There seems to be an issue in the parallel manager with clang. 
I am aware that this is tangential to jitcode, but wondered if in 
the meantime you found some fix to it. 

Thanks in advance for all your help. 
best, i-

**Comment by hokanoei** [comment]
@Wrzlprmft thanks a lot for your kind help in this! Following your instructions:  

- checked version of jitcxde-common: 1.5.2 --> the issue with jitcode.test() persists;
- tried using only gcc (updated to latest version) --> idem; 
- specified the compiler via ode.compile_C after importing jitcode --> no combination worked.

I did not try downgrading to/installing a previous version of Clang (it seems that the best 
way for doing that is to install a previous version of xcode which is a bit of an overshooting). 

What has worked: I have commented the line specifying the compiler in the python script, i.e. 

from jitcode import jitcode, y
ODE = jitcode( [y(1),-y(0)] )
ODE.generate_f_C(chunk_size=1)
#ODE.compile_C(omp=(["-fopenmp"],["-fopenmp"]))
ODE.set_integrator("dopri5")
ODE.set_initial_value([1,2])
ODE.integrate(0.1)

I have run a few test scripts with jitcode without specifying the compiler and they all worked, 
both in IDEs and bash. However (and a bit oddly) the issue with jitcode.test() still remains. 

Is it possible that jitcode.test tries calling clang/gcc through obsolete dependencies?

Besides the above issue with jitcode.test(), I would say the thread is solved 
since the parallel coding in C appears to be working correctly.

**Comment by Wrzlprmft** [comment]
> tried using only gcc (updated to latest version) --> idem;

Just to double-check: How did you do that and did you check that it worked (e.g., with `ODE.compile_C(…,verbose=True)`)?

> I did not try downgrading to/installing a previous version of Clang (it seems that the best way for doing that is to install a previous version of xcode which is a bit of an overshooting).

That’s not what I was suggesting. The problem appears to be that the Clang that comes with [MacOS (via Xcode) is not built with OpenMP support](https://medium.com/@asvetly/clang-openmp-setup-in-macos-dbb0638cc4df) for some reason. Thus, if you manually install Clang (even the same version) this may solve the issue. (Mind that I have no idea whether the linked source is a good way to do that.)

> What has worked: I have commented the line specifying the compiler in the python script, […]

Well, that would also deactivate OpenMP. Without `ODE.compile_C(omp=…)` you get no OpenMP.

> However (and a bit oddly) the issue with jitcode.test() still remains.

`test` tests OpenMP explicitly unless you tell it not to (`jitcode.test(omp=False)`). So that’s no surprise.

> Is it possible that jitcode.test tries calling clang/gcc through obsolete dependencies?

No, it essentially executes the script I made you run.

> the parallel coding in C appears to be working correctly.

Due to the above, I doubt that.

**Comment by hokanoei** [comment]
Thanks again for your careful and patient support! 

> Just to double-check: How did you do that and did you check that it worked (e.g., with `ODE.compile_C(…,verbose=True)`)?

I changed the CC flag to gcc and later to clang via os to test "jitcode.test()" as follows: 

>>>import os, jitcode
>>>os.environ["CC"] = "gcc" 
>>>jitcode.test()

>>>clang: error: unsupported option '-fopenmp'
>>>error: command 'gcc' failed with exit status 1

> That’s not what I was suggesting. The problem appears to be that the Clang that comes with [MacOS (via Xcode) is not built with OpenMP support](https://medium.com/@asvetly/clang-openmp-setup-in-macos-dbb0638cc4df) for some reason. Thus, if you manually install Clang (even the same version) this may solve the issue. (Mind that I have no idea whether the linked source is a good way to do that.)

Thanks, and apologies for my misunderstanding. I did follow Bruno Grieder's solution [here](https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave) but I was not able to include directories and link directories in CMakeList.txt as suggested there. Using brew install llvm libomp should have installed Clang independently from the Xcode version, right?

> Well, that would also deactivate OpenMP. Without `ODE.compile_C(omp=…)` you get no OpenMP.

Hence no parallelization, I see. Perhaps I need to specify to compilers where llvm is? Something like: 
>> export LDFLAGS="-L/usr/local/opt/llvm/lib"
>> export CPPFLAGS="-I/usr/local/opt/llvm/include"

> @Wrzlprmft thanks a lot for your kind help in this! Following your instructions:
> 
> * checked version of jitcxde-common: 1.5.2 --> the issue with jitcode.test() persists;
> * tried using only gcc (updated to latest version) --> idem;
> * specified the compiler via ode.compile_C after importing jitcode --> no combination worked.
> 
> I did not try downgrading to/installing a previous version of Clang (it seems that the best
> way for doing that is to install a previous version of xcode which is a bit of an overshooting).
> 
> What has worked: I have commented the line specifying the compiler in the python script, i.e.
> 
> ```python
> from jitcode import jitcode, y
> ODE = jitcode( [y(1),-y(0)] )
> ODE.generate_f_C(chunk_size=1)
> #ODE.compile_C(omp=(["-fopenmp"],["-fopenmp"]))
> ODE.set_integrator("dopri5")
> ODE.set_initial_value([1,2])
> ODE.integrate(0.1)
> ```
> 
> I have run a few test scripts with jitcode without specifying the compiler and they all worked,
> both in IDEs and bash. However (and a bit oddly) the issue with jitcode.test() still remains.
> 
> Is it possible that jitcode.test tries calling clang/gcc through obsolete dependencies?
> 
> Besides the above issue with jitcode.test(), I would say the thread is solved
> since the parallel coding in C appears to be working correctly.

**Comment by hokanoei** [comment]
Thanks a lot for your careful and patient support!

**Comment by hokanoei** [comment]
Thanks for your careful and patient support! You were very right. 

> Thus, if you manually install Clang (even the same version) this may solve the issue. (Mind that I have no idea whether the linked source is a good way to do that.)

Prior to opening this issue I have been following the solution suggested by [Bruno Grieder in stackoverflow](https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave), so I installed manually llvm and libomp. I have reinstalled them now to be sure. Using "clang" to flag the CC compiler seems to be calling a version of clang that does not support OpenMP.

By flagging instead the correct clang in python via os, I do not get anymore the error when testing jitcode: 

```python 
>>> import jitcode
>>> import os
>>> os.environ["CC"] = "/usr/local/opt/llvm/bin/clang"
>>> jitcode.test()
```

Going back now to your running example with -fopenmp: 

```python
>>>import os
>>>os.environ["CC"] = "/usr/local/opt/llvm/bin/clang"
>>>from jitcode import jitcode, y
>>>ODE = jitcode( [y(1),-y(0)] )
>>>ODE.generate_f_C(chunk_size=1)
>>>ODE.compile_C(omp=(["-fopenmp"],["-fopenmp"]))
>>>ODE.set_integrator("dopri5")
>>>ODE.set_initial_value([1,2])
>>>ODE.integrate(0.1)
Out[1]: array([1.194671  , 1.89017491])
```

I tried using also "gcc" instead of "clang" but that kept giving issues. 
I would say the issue is closed unless I am missing something deeper.
