### ISSUE TITLE
is that a typo in documentation: A more complicated example

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcode#20]
I am just following the [documentation](https://jitcode.readthedocs.io/en/v1.6.0/#)
and in the section `A more complicated example`
the third component of the equation should be 

```
\dot{z}_i &= b + z_i (x_i -c) + k \sin(t) \sum_{j=0}^N (z_j-z_i) 
```
right?
because at helper and the line 34 of the code we have:
`helpers = [( sum_z, sum( y(3*j+2) for j in range(N) ) )]
coupling_term_2 = k * (sum_z-N*y(3*i+2))`

or there is a trick that I don't get?

**Comment by Wrzlprmft** [comment]
No, I somehow mixed things up, in the text not the code though. It should be [fixed now](https://jitcode.readthedocs.io/en/latest/#module-SW_of_Roesslers). Thanks for reporting.
