### ISSUE TITLE
confine the number of threads using OMP

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcode#24]
Hi,

We can confine the number if threads using in OpenMP with environment variable 
`export OMP_NUM_THREADS=n`
but still sometimes we need to have a control on the number of threads at the running.
Is there any option for controlling the number of threads inside the code?

I could find it at `compile_C` function source code.

Ununtu 18.04, jitcode v 1.6.0
 
best,

**Comment by Wrzlprmft** [comment]
Currently, this is not possible.

What can be done is allowing to limit the number of threads at compile time, however, this would be some work to implement and I don’t see a big advantage of this.

A fine-grained thread control, i.e.: “Do this with two threads and this with four threads.” would be even more difficult to implement.

May I ask why you need this?

**Comment by Ziaeemehr** [comment]
OK no problem.
We usually use a shared cluster with about 26 cores that I don't want to use all core.
I just prepare a bunch of jobs and send them to the machine. With environment variable we have loose control on threads of each script (for example submitted with `joblib`).
but I think it's not crucial to have it.

**Comment by Wrzlprmft** [comment]
Why does the environment variable not work here?

Anyway, if you really need this, a quick and dirty solution would be to put `omp_set_num_threads()` with your desired number of threads into [`jitced_template.c`](https://github.com/neurophysik/jitcode/blob/master/jitcode/jitced_template.c) at a suitable place.

Finally, please mind that if you are running multiple realisations, it’s almost always better to use one core for each of them instead of using OMP.

**Comment by Ziaeemehr** [comment]
The environment variable works but it is the same for all active runs.
Cool, Yes I read about the optimization in the paper.
thank you,
best,

**Comment by Wrzlprmft** [comment]
> The environment variable works but I think it is the same for all active runs.

This depends somewhat on what system you use to manage your runs, but in a good system, you should be able to set environment variables separately. Contrary to what the name might suggest, environment variables are not necessarily global. I can have one shell with `OMP_NUM_THREADS=2` and one with `OMP_NUM_THREADS=4`.
