### ISSUE TITLE
paralleling using joblib

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcode#28]
Hi, 
Maybe it's not directly an issue of jitcode but can help for paralleling.
I use joblib to parallel the code and to pass different matrix to the model I defined the model inside the main simulation function.
The main function then with a list of parameters passed to joblib.

The problem is defining the function `kuramotos_f_II` inside simulate_lyap raise an error :

```sh
raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```

I removed extra codes for simplicity:

```python
import os
import numpy as np
from symengine import sin, Symbol
from jitcode import y
from joblib import Parallel, delayed


os.environ["CC"] = "clang"


def simulate_lyap(coupling, adj):

    def kuramotos_f_II():
        for i in range(N):
            coupling_sum = sum(sin(y(j)-y(i))
                               for j in range(N)
                               if adj[i, j])
            yield omega[i] + g * coupling_sum

    print("compiling .............................................")


def run_command(args):
    coupling, adj = args
    simulate_lyap(coupling, adj)
# -------------------------------------------------------------------


def batch_run():

    args = []
    for label in labels:
        adj = net[label]
        args.append([coupling, adj])
    Parallel(n_jobs=n_jobs)(map(delayed(run_command), args))


if __name__ == "__main__":

    n_jobs = 2
    N = 3
    coupling = 0.05

    labels = ["FB", "FF"]
    FF = np.asarray([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0]])
    FB = np.asarray([[0, 0, 1],
                     [1, 0, 0],
                     [0, 1, 0]])
    g = Symbol("g")
    omega = np.random.normal(0, 0.1, size=N)
    net = {"FB": FB,
           "FF": FF}
    batch_run()
```

**Comment by Ziaeemehr** [comment]
I just put the function out of the `simulate_lyap` and it resolved the issue but I still have the same error if I add jitcode_lyap inside the fucntion and pass it to joblib

```python
def kuramotos_f_II():
    for i in range(N):
        coupling_sum = sum(sin(y(j)-y(i))
                           for j in range(N)
                           if adj[i, j])
        yield omega[i] + g * coupling_sum


def simulate_lyap(coupling, adj):

    print("compiling .............................................")

    I = jitcode_lyap(kuramotos_f_II,
                     n=N,
                     n_lyap=n_lyap,
                     simplify=False,
                     control_pars=[g])


def run_command(args):
    coupling, adj = args
    simulate_lyap(coupling, adj)
# -------------------------------------------------------------------

    

if __name__ == "__main__":

    n_jobs = 2
    N = 3
    coupling = 0.05

    labels = ["FB", "FF"]
    FF = np.asarray([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0]])
    FB = np.asarray([[0, 0, 1],
                     [1, 0, 0],
                     [0, 1, 0]])
    g = Symbol("g")
    omega = np.random.normal(0, 0.1, size=N)
    net = {"FB": FB,
           "FF": FF}
    args = []
    for label in labels:
        adj = net[label]
        args.append([coupling, adj])
    Parallel(n_jobs=n_jobs)(map(delayed(run_command), args))
```

**Comment by Wrzlprmft** [comment]
I fail to keep track of what happens when and how it is parallelised, but I presume that you have a problem with namespaces, as you rely a lot on namespaces defaulting to the right thing.

As for pickling, mind that `jitcode` instances cannot be pickled anyway and I don’t see a big need to pickle something, so if you can, I would just disable pickling.

**Comment by Ziaeemehr** [comment]
Sorry, I am not explaining clearly.
For an example to test, I considered the Kuramoto model, for 2 different adjacency matrix and for each case I run the simulation for different couplings.

The compiling part run in serial, I save the `.so` file and then run the simulation in parallel for different couplings.
In this way I did not get any pickle error anymore.
I tried to be careful about the namespace.


```python
def run_command(args):
    coupling, label = args
    simulate_lyap(coupling, label)  # run the simulation , use  *.so file
# -------------------------------------------------------------------

# pass the list of parameters to run_command and run in parallel
def batch_run():
    args = []
    for label in labels:
        for coupling in couplings:
            args.append([coupling, label])
    Parallel(n_jobs=n_jobs)(map(delayed(run_command), args))


# compile serial
for label in labels:
    adj = net[label]
    compiling(N, n_lyap, label, adj, USE_OMP)

batch_run()
```

please let me know if something seems wrong or could be done better.
I put the code [here](https://github.com/Ziaeemehr/Kuramoto_model/blob/main/examples/jitcode/lyapunov/main_lyap_batch.py) in case you want to check.
best,

**Comment by Wrzlprmft** [comment]
I see no immediate problem with the code (and  IIUC you don’t have any problems anymore).

One idea came to mind regarding your pickling issue: Could it be that your parallelising software pickles everything that hasn’t been garbage-collected at some point? If yes, it might help to explicitly destroy the objects causing problems using `del` when they are not needed anymore.
