### ISSUE TITLE
Control parameters initially set to zero

### ISSUE THREAD

**Issue by omaarattia** [neurophysik/jitcode#29]
Hello,

I am using JITCODE for few months, and I have recently encountered a problem when I switched to a new computer.
It seems that control parameters are initially set to zero independently of what is passed to `set_parameters`.

Here is a minimal example:
```
import symengine
import numpy as np
from jitcode import jitcode

c = 1.
c_sym = symengine.Symbol('c_sym')

def f():
    yield c_sym
    
ODE = jitcode(f, control_pars=[c_sym], verbose=False)
ODE.set_integrator("DOP853")
ODE.set_initial_value(np.array([0.]), 0.0)
ODE.set_parameters(c)

ODE.integrate(1.)
```

I changed the Scipy source code to print the derivative at each step. The output of the previous code is the following:
```
[0.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
```

As you can see, the first value of the derivative is equal to 0, even though the control parameter is set to 1 beforehand.

This is problematic because if we imagine a different function `f`, let's say:
```
def f():
    yield 1./c_sym
```

The integrator crashes, even though it is not supposed to:
```
[inf]
---------------------------------------------------------------------------
UnsuccessfulIntegration                   Traceback (most recent call last)
<ipython-input-12-675a00b12876> in <module>
     10 ODE.set_parameters(c)
     11 
---> 12 ODE.integrate(1.)

~/anaconda3/lib/python3.8/site-packages/jitcode/_jitcode.py in integrate(self, *args, **kwargs)
    654 
    655         def integrate(self,*args,**kwargs):
--> 656                 return self.integrator.integrate(*args,**kwargs)
    657 
    658         def successful(self):

~/anaconda3/lib/python3.8/site-packages/jitcode/integrator_tools.py in integrate(self, t)
     91                         self.backend.step()
     92                         if self.backend.status == "failed":
---> 93                                 raise UnsuccessfulIntegration
     94                 self.kwargs["y0"] = self.backend.dense_output()(t)
     95                 self.kwargs["t0"] = t

UnsuccessfulIntegration: 
```

As you can see, the code only performed one single integration step before crashing because the derivative is `inf`.

Is there a problem on my side? I tried updating/changing the C compilator but nothing changes. I also tried to change the integrator, but it is the same behavior for all `solve_ivp` methods, while for `ode` methods the integrator runs without nothing happening (I guess the step size just becomes infinitely smaller and smaller).
My JITCODE version is 1.6.0 and my Python version is 3.8.5.

Thank you very much!

**Comment by Wrzlprmft** [comment]
It looks like some changes in Solve IVP cause for the derivative to be called before integration (to estimate step sizes, I presume). As a quick fix, swap `set_initial_value` and `set_parameters` and everything should be fine. A more thorough fix is on the way.

> for `ode` methods the integrator runs without nothing happening (I guess the step size just becomes infinitely smaller and smaller).

The ODE integrator should finish just fine; at least it does so for me.

Thanks for reporting and thanks for using a minimal example.

**Comment by omaarattia** [comment]
Thank you very much for taking the time to understand the problem and provide me with a solution.
I tried and it works.
And kudos for having developed such an awesome module!
