### ISSUE TITLE
error: Number of values does not match number of control parameters, using the "*.so" file

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcode#32]
I have defined a class to solve Jansen-Rit model:
Let's focuse on `compile` and `simulate` functions.

```python

class jr:
    def derivative(self):
         # some code to define dy/dt
    
    def compile(self):
        I = jitcode(self.derivative, n=dim,
                    control_pars=[PAR_C0])
        I.generate_f_C()
        I.compile_C(omp=False)
        I.save_compiled(overwrite=True, destination="jr.so")

    def simulate(self, par):
        I = jitcode(n=dim,
                    module_location="jr.so")

        I.set_parameters(par)
        I.set_integrator(method)
        I.set_initial_value(initial_condition, t_initial)
``` 

When I only have simulate function i.e. if I don't try to use the compiled ".so" file like below:

```python
def simulate(self, par):

        I = jitcode(self.derivative, n=dim,
                    control_pars=[PAR_C0])
        I.generate_f_C()
        I.compile_C(omp=False)

        I.set_parameters(par)
        I.set_integrator(method)
        I.set_initial_value(initial_condition, t_initial)
```
It works properly, but when I seperate the compilation part and store the `.so` file and try to use it in `simulate` function (like the code at the top of the question) I get the following weird error:
```sh
compiled C code
Traceback (most recent call last):
  File "jr_class_seperate_compile.py", line 85, in <module>
    SOL.simulate(C0)
  File "jr_class_seperate_compile.py", line 43, in simulate
    I.set_parameters(par)
  File "/home/ziaee/.local/lib/python3.8/site-packages/jitcode/_jitcode.py", line 655, in set_parameters
    raise ValueError("Number of values does not match number of control parameters.")
ValueError: Number of values does not match number of control parameters.
```

I am passing only a single parameter to `simulate` function, why it says the problem is in number of values?

I have attached the full code in case you want to reproduce the error.
sorry for the long code but I just need to know if I am wrong somewhere or there is some limitation in usage.
[jansen-rit.zip](https://github.com/neurophysik/jitcode/files/6801873/jansen-rit.zip)

**Comment by Wrzlprmft** [comment]
You have to pass the control parameters again when instantiating `jitcode` again using `module_location`. I admit that I could have handled this part of the interface better – maybe in the next big version, when I do not need to care about backwards compatibility. I also could have documented this better, which I now do.
