### ISSUE TITLE
use_omp does not make threads

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcode#33]
Hello dear developers,
I am using the following code for the Kuramoto model and I am trying to run the code in parallel, but I don't know what is missing that the code runs sequentioally.

I look htop  to see the number of running threads and also check the time to get an speed up.
here is my try:

```python

    def kuramotos():

        for i in range(N):
            interaction = sum(sin(y(j)-y(i)) for j in range(N) if adj[i, j])
            yield omega[i] + coupling * interaction

    coupling = Symbol("coupling")
    
    I = jitcode(kuramotos, n=N, control_pars=[coupling])
    I.generate_f_C()
    I.compile_C(omp=True)
    I.save_compiled(overwrite=True, destination="KM.so")

    print("Compile time : {:.3f} seconds.".format(time()- compile_time))


    start_time = time()
    for i in range(len(couplings)):
        for j in range(num_ensembles):

            phases = np.zeros((len(times), N))
            I = jitcode(n=N,
                        control_pars=[coupling],
                        module_location="KM.so")
            I.set_integrator(name="RK23")
            I.set_parameters(couplings[i])
            I.set_initial_value(initial_state, time=0.0)

            for k in range(len(times)):
                phases[k, :] = I.integrate(times[k]) % (2*np.pi)
```
I upload the full code in case you want to check.
[04_kuramoto.py.zip](https://github.com/neurophysik/jitcode/files/6907571/04_kuramoto.py.zip)

I use version 1.7.0 on Ubuntu 20.04.
regards,
Abolfazl

**Comment by Wrzlprmft** [comment]
The size of parallelised chunks is governed by the parameter `chunk_size`, which defaults to `100`. As your system size is `N=50`, you won’t see an effect without reducing `chunk_size`. For example, if you use `I.generate_f_C(chunk_size=17)`, you should three cores being used.

Be aware that for the sizes in your example, OMP is probably not yielding much improvement. Parallelising your different scenarios (`ensembles` and `couplings`) is probably a much better way to use parallelisation than parallelising the internals of individual integrations.

**Comment by Ziaeemehr** [comment]
I put N=100, chunk_size=25, maybe I am missing somthing, I still have a single thread.
Yeah you are right, OMP is not a proper method here, this is just an over simplified example.

Do you get multiple threads?

**Comment by Ziaeemehr** [comment]
Great, Thank you.
