### ISSUE TITLE
AttributeError: 'jitcode_lyap' object has no attribute 'n_lyap'

### ISSUE THREAD

**Issue by vdeltatto** [neurophysik/jitcode#38]
Dear developers,

I am trying using jitcode to compute the Lyapunov exponents of a dynamical system. When I run the example in [this page](https://jitcode.readthedocs.io/en/latest/#example) below the section _Calculating Lyapunov exponents with jitcode_lyap_, I experience the error reported in the attached image. I did not carry out any modification to the lines of code of the example. 

<img width="769" alt="AttributeError_jitcode_lyap" src="https://user-images.githubusercontent.com/53079470/181303646-1dacad40-3504-4590-bb7a-b8fe6038af00.png">

Thank you for your help.

Vittorio

**Comment by Wrzlprmft** [comment]
I fail to reproduce the error. Can you tell me which version of `jitcode` and `jitcxde_common` you are using? (Run `import jitcode; print(jitcode.__version__)`.)

**Comment by vdeltatto** [comment]
I am using version 1.7.1. I just tried with an older version (1.6.0) and I don't see that error anymore.

**Comment by Wrzlprmft** [comment]
Ah, your link points to the wrong example and I blindly tried that, not realising that it doesn’t even feature Lyapunov exponents. I can now reproduce your error. 

I will investigate and fix this (be it by reverting the respective code) soon. The main mystery is why the tests did not catch this. Until then, you should be fine with any version up to 1.7.0.

**Comment by Wrzlprmft** [comment]
This should now be fixed. Thanks for reporting!
