### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by drsaroj** [neurophysik/jitcode#39]
Unable to install on MacOS 13 with Xcode 14.0.1

-------------------------------------------
pip3 install \
        git+git://github.com/neurophysik/jitcxde_common \
        git+git://github.com/neurophysik/jitcode \
        git+git://github.com/neurophysik/jitcdde \
        git+git://github.com/neurophysik/jitcsde \
        --no-dependencies --user
Collecting git+git://github.com/neurophysik/jitcxde_common
  Cloning git://github.com/neurophysik/jitcxde_common to /private/var/folders/0y/w021bgn16936pgg4f_7f94xc0000gn/T/pip-req-build-cnm2bu_6
  Running command git clone --filter=blob:none --quiet git://github.com/neurophysik/jitcxde_common /private/var/folders/0y/w021bgn16936pgg4f_7f94xc0000gn/T/pip-req-build-cnm2bu_6
  fatal: unable to connect to github.com:
  github.com[0: 20.207.73.82]: errno=Operation timed out

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/neurophysik/jitcxde_common /private/var/folders/0y/w021bgn16936pgg4f_7f94xc0000gn/T/pip-req-build-cnm2bu_6 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/neurophysik/jitcxde_common /private/var/folders/0y/w021bgn16936pgg4f_7f94xc0000gn/T/pip-req-build-cnm2bu_6 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

------------------------------------------

**Comment by Wrzlprmft** [comment]
You seem to be using old installation instructions. `pip3 install git+git://github.com/…` doesn’t work anymore. You need to use `pip3 install git+https://github.com/…` instead. I already updated the [documentation](https://jitcde-common.readthedocs.io/en/latest/#building-from-source) in April (I just noted that I missed one instance, but that’s not the one you have been using).

**Comment by drsaroj** [comment]
Thank you so much for response. Now it is working fine.
