### ISSUE TITLE
Apple Silicone Error

### ISSUE THREAD

**Issue by drsaroj** [neurophysik/jitcode#40]
Before you post an issue, please check the following (if applicable):

* Read [this FAQ](https://jitcde-common.readthedocs.io/#common-mistakes-and-questions).

* Provide [a minimal and complete example](https://stackoverflow.com/help/mcve). In particular consider that I cannot know what control parameters you are using. It makes my life considerably easier and you will likely get a helpful answer earlier. Also, there is a chance that you will solve your problem yourself.

* State your JiTC\*DE version (`jitcode.__version__` or similar). If it’s reasonably possible for you, try updating to the newest version first, in particular if yours is still smaller than 1.0.

**Comment by drsaroj** [comment]
I have moved to a new system which is Apple M1Max having 64gb RAM and running macOS 13.4.1.

I have jitcode==1.7.2 installed and on running I am getting the following errors now

-----------------------------

running build_ext
building 'jitced' extension
creating /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/var
creating /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/var/folders
creating /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/var/folders/gx
creating /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn
creating /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T
creating /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/drsarojkumar/Library/Python/3.11/lib/python/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/jitced.c -o /var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/var/folders/gx/_k5tjwln7bv3j1j268gp2zrh0000gn/T/jitcxde_193b0yfc/jitced.o -std=c11 -Ofast -g0 -mtune=native -Wno-unknown-pragmas
error: unknown target CPU 'apple-m1'
note: valid target CPU values are: i386, i486, winchip-c6, winchip2, c3, i586, pentium, pentium-mmx, pentiumpro, i686, pentium2, pentium3, pentium3m, pentium-m, c3-2, yonah, pentium4, pentium4m, prescott, nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, lakemont, k6, k6-2, k6-3, athlon, athlon-tbird, athlon-xp, athlon-mp, athlon-4, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, geode
error: command '/usr/bin/clang' failed with exit code 1

--------------------------------

**Comment by Wrzlprmft** [comment]
This appears to be a problem with the underlying compilation architecture not being aligned with some changes by Apple. Since JiTC*DE doesn’t set any architecture-specific flags or similar, I don’t see what I can do about this. I suggest to try the following things:

* Update Clang or switch to GCC.
* Update Setuptools.
* Add a [custom compiler flag](https://jitcde-common.readthedocs.io/en/latest/#compiler-and-linker-arguments) overriding `-arch arm64 -arch x86_64` with whatever is appropriate for your machine.
* Same as above just with `-mtune=native`.
