### ISSUE TITLE
Installing jitcode and its dependencies

### ISSUE THREAD

**Issue by xoviat** [neurophysik/jitcode#6]
First attempt:

```
conda install -y python-symengine
```

Result:

```
E   Your version of SymEngine is too low. Unless a new version of SymEngine was released recently (see https://github.com/symengine/symengine.py/issues/204), you can only address this by building SymEngine from source. See http://jitcde-common.readthedocs.io/#building-from-source for instructions.
E   ===============================================
```

Second try:

```
conda install -c symengine/label/dev python-symengine
```

Result:

```
appdata\local\temp\tmpoi9xa56y\f.c(4): error C2065: 'M_E': undeclared identifier
```

What's the next try?

**Comment by xoviat** [comment]
cc @Wrzlprmft

**Comment by isuruf** [comment]
@xoviat, you can try the newest packages at `symengine/label/dev`

**Comment by xoviat** [comment]
Thanks.

@Wrzlprmft Please release jitcxde_common

**Comment by Wrzlprmft** [comment]
@xoviat @isuruf 
Can I specify those as a dependency for PyPI and similar, and if yes, how?

**Comment by isuruf** [comment]
@Wrzlprmft, I just uploaded dev version and manylinux wheels. (OSX builds are failing - https://github.com/symengine/symengine-wheels/issues/1, windows is also failing, but I know the fix for it)

You can add `symengine>=0.3.1.dev0` as a dependency and the dev versions will be installed.

**Comment by Wrzlprmft** [comment]
> Please release jitcxde_common

@xoviat: Done.

@isuruf: Splendid.
