### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by thallatt** [neurophysik/jitcode#9]
I am having issues installing Jitcode related to CMake. Attempting to install Jitcode via the command:

sudo pip3 install jitcode

produces the following error message:

...
Installing collected packages: symengine, jitcxde-common, jitcode
  Found existing installation: symengine 0.3.0
    Uninstalling symengine-0.3.0:
      Successfully uninstalled symengine-0.3.0
  Running setup.py install for symengine ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-fygx1bx1/symengine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext --symengine-dir=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/symengine install --record /private/tmp/pip-record-fiwztb4b/install-record.txt --single-version-externally-managed --compile:
    running build_ext
    -- The C compiler identification is AppleClang 10.0.0.10001044
    -- The CXX compiler identification is AppleClang 10.0.0.10001044
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:5 (find_package):
      Could not find a package configuration file provided by "SymEngine"
      (requested version 0.3.0) with any of the following names:
    
        SymEngineConfig.cmake
        symengine-config.cmake
    
      Add the installation prefix of "SymEngine" to CMAKE_PREFIX_PATH or set
      "SymEngine_DIR" to a directory containing one of the above files.  If
      "SymEngine" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-fygx1bx1/symengine/build/lib.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    error: error calling cmake
    
    ----------------------------------------
  Rolling back uninstall of symengine

I have tried modifying the CMAKE_PREFIX_PATH via:

 cmake -DCMAKE_PREFIX_PATH=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/symengine

to no avail.

Perhaps my understanding of CMake is the issue here, and not with jitcode. Thoughts on any resolution to this would be greatly appreciated.

**Comment by Wrzlprmft** [comment]
As you suspected, this is not an issue of JiTCODE, but of SymEngine or CMake, probably the former. I suggest to report it [here](https://github.com/symengine/symengine.py/issues/).
